### ISSUE TITLE
TODO : Screens 

### ISSUE THREAD

**Issue by rishacha** [rishacha/stackhack#3]
## Subtasks ( Can be changed ) 
- [ ] Login Screen
    - [ ] Google Auth
    - [ ] FB Auth
    - [ ] User Model
    - [ ] Passport Auth strategy
- [ ] Tasks Display Screen (CRUD)
    - [ ] Add task
    - [ ] Complete task
    - [ ] In Progress
    - [ ] Remove Task
    - [ ] Reminder/Calendar integration
    - [ ] Labels ( Personal, Work, etc. )
    - [ ] Subtasks
    - [ ] Time left/Overdue
- [ ] User Account Screen
- [ ] (Optional) Alerts
- [ ] Documentation
